sever:
  port: 8080

spring:
  application:
    name: MyLedger

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myledger?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user1
    password: 1234


mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  upload:
    path: upload